"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 00:57:18.563317
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajustes',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('paquetes',
    sa.Column('clave', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('precio_usd', sa.Float(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('planes',
    sa.Column('clave', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('precio_usd_mes', sa.Float(), nullable=False),
    sa.Column('minutos_mes', sa.Float(), nullable=False),
    sa.Column('creditos_mes', sa.Integer(), nullable=False),
    sa.Column('tope_acumulado_meses', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('precios',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('costo_ref_usd', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('a_costo', sa.Boolean(), nullable=False),
    sa.Column('proveedor_login', sa.String(length=30), nullable=True),
    sa.Column('id_externo', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('espacios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('dueno_id', sa.String(length=32), nullable=False),
    sa.Column('moneda_vista', sa.String(length=3), nullable=False),
    sa.Column('numero_registro', sa.Integer(), nullable=False),
    sa.Column('onboarding_hecho', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ruta', sa.String(length=400), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('estilos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('origen', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('estilos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estilos_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('formulas_guion',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('origen', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('formulas_guion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formulas_guion_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('miembros',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('usuario_id', sa.String(length=32), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'usuario_id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('referencia', sa.String(length=30), nullable=False),
    sa.Column('precio_usd', sa.Float(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('pasarela', sa.String(length=30), nullable=True),
    sa.Column('referencia_externa', sa.String(length=120), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('perfiles_edicion',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('origen', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('perfiles_edicion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perfiles_edicion_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('plantillas_miniatura',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('origen', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('plantillas_miniatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantillas_miniatura_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('suscripciones',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('plan_clave', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referencia_externa', sa.String(length=120), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_clave'], ['planes.clave'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id')
    )
    op.create_table('voces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('origen', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('voces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voces_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('personajes',
    sa.Column('estilo_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('origen', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estilo_id'], ['estilos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personajes_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('canales',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('idioma', sa.String(length=10), nullable=False),
    sa.Column('estilo_id', sa.String(length=32), nullable=True),
    sa.Column('personaje_id', sa.String(length=32), nullable=True),
    sa.Column('voz_id', sa.String(length=32), nullable=True),
    sa.Column('formula_id', sa.String(length=32), nullable=True),
    sa.Column('plantilla_miniatura_id', sa.String(length=32), nullable=True),
    sa.Column('perfil_edicion_id', sa.String(length=32), nullable=True),
    sa.Column('ajustes', sa.JSON(), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estilo_id'], ['estilos.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas_guion.id'], ),
    sa.ForeignKeyConstraint(['perfil_edicion_id'], ['perfiles_edicion.id'], ),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['plantilla_miniatura_id'], ['plantillas_miniatura.id'], ),
    sa.ForeignKeyConstraint(['voz_id'], ['voces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'clave')
    )
    with op.batch_alter_table('canales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canales_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('canal_id', sa.String(length=32), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('carpeta', sa.String(length=300), nullable=False),
    sa.Column('minutos', sa.Float(), nullable=True),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canales.id'], ),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_id', 'slug')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('usuario_id', sa.String(length=32), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('costo_estimado_usd', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_espacio_id'), ['espacio_id'], unique=False)

    op.create_table('movimientos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('espacio_id', sa.String(length=32), nullable=False),
    sa.Column('usuario_id', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('reserva_id', sa.String(length=32), nullable=True),
    sa.Column('costo_real_usd', sa.Float(), nullable=False),
    sa.Column('precio_cliente_usd', sa.Float(), nullable=False),
    sa.Column('pedido_id', sa.String(length=32), nullable=True),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_creado'), ['creado'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_espacio_id'), ['espacio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_reserva_id'), ['reserva_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_video_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_reserva_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_espacio_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_creado'))

    op.drop_table('movimientos')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_espacio_id'))

    op.drop_table('reservas')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_espacio_id'))

    op.drop_table('videos')
    with op.batch_alter_table('canales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canales_espacio_id'))

    op.drop_table('canales')
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personajes_espacio_id'))

    op.drop_table('personajes')
    with op.batch_alter_table('voces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voces_espacio_id'))

    op.drop_table('voces')
    op.drop_table('suscripciones')
    with op.batch_alter_table('plantillas_miniatura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantillas_miniatura_espacio_id'))

    op.drop_table('plantillas_miniatura')
    with op.batch_alter_table('perfiles_edicion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perfiles_edicion_espacio_id'))

    op.drop_table('perfiles_edicion')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_espacio_id'))

    op.drop_table('pedidos')
    op.drop_table('miembros')
    with op.batch_alter_table('formulas_guion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formulas_guion_espacio_id'))

    op.drop_table('formulas_guion')
    with op.batch_alter_table('estilos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estilos_espacio_id'))

    op.drop_table('estilos')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_espacio_id'))

    op.drop_table('assets')
    op.drop_table('espacios')
    op.drop_table('usuarios')
    op.drop_table('precios')
    op.drop_table('planes')
    op.drop_table('paquetes')
    op.drop_table('ajustes')
    # ### end Alembic commands ###
