"""bolsa de creditos

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 01:00:18.492765
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bolsa', sa.String(length=10), nullable=False, server_default='recarga'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_column('bolsa')

    # ### end Alembic commands ###
